name: Node.js CI

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ${{ matrix.os }} #ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node-version: [16.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/